---
title: Lab Intro
subtitle: "Lab 3 Common trends in plankton data"
author: "Mark Scheuerell"
date: "Due May 6, 2025"
output: 
  html_document:
    code-folding: true
    toc: true
    toc_float: true
---

```{r setup, echo = FALSE, message = FALSE}
options(dplyr.summarise.inform = FALSE)
```

## Background

For this lab you will use dynamic factor analysis (DFA) to examine common temporal patterns in plankton data from Lake Washington. These data are a bit noisy and gappy, so you will need to make some choices about which species and time period(s) to examine.


## Teams

Team 1: Anna, Mary, Emma

Team 2: Matheus, Brian, Tina

Team 3: Ben, Nicole, Lilac


## Lake Washington data

For reference, here are the columns in the Lake Washington data set:

### Indices

* `Year`: year  
* `Month`: month as an integer  

### Environmental data

* `Temp`: water temperature in degrees C  
* `TP`: total phosphorous concentration in mg m<sup>-3</sup>  
* `pH`: pH. 

### Phytoplankton

* `Cryptomonas`: small brown or green algae (edible)  
* `Diatoms`: small algae rich in silica (edible)  
* `Greens`: general class of algae (edible)  
* `Bluegreens`: cyanobacteria that can fix nitrogen (inedible)  
* `Unicells`: very small algae (edible)  
* `Other.algae`: generic catch-all for atypical species (edible)  

### Zooplankton

* `Conochilus`: colonial form of rotifer (grazer)  
* `Cyclops`: cyclopoid copepod (grazer)  
* `Daphnia`: cladoceran (grazer)  
* `Diaptomus`: calanoid copepod (grazer)  
* `Epischura`: very large calanoid copepod (predator)  
* `Leptodora`: very large cladoceran (predator)  
* `Neomysis`: opossum shrimp (predator)  
* `Non.daphnid.cladocerans`: catch-all for other cladocerans (grazers)
* `Non.colonial.rotifers`: free-floating rotifers (grazers)


## Tasks

1. Plot time series of densities for the different taxa and environmental covariates.

2. Select an appropriate time period of at least 5 years (60 months) and fit different forms of DFA models with and without covariates.

3. Evaluate the model fits relative to the observed data for your best (or top 3) models. 


## Resources

Lab materials from April 20 [[online here](https://atsa-es.github.io/atsa/Labs/Week%204/intro-to-dfa.html)]

Chapter 10 Dynamic Factor Analysis. ATSA Lab Book. [[online here](https://atsa-es.github.io/atsa-labs/sec-dfa.html)]


